//
//  TextModel.swift
//  TextureTestApp
//
// 
//

import Foundation

struct TextModel {
    static let shared = TextModel()
    private init() { }
    let text = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi velit orci, convallis ut eros et, lacinia rhoncus risus. Praesent gravida sit amet turpis eu laoreet. Sed at vulputate ex, quis fermentum nulla. Vivamus mattis fringilla posuere. Cras tristique turpis non nisi fringilla consectetur. Mauris vel odio elementum, consectetur lectus at, suscipit velit. Vivamus quis odio ultrices, pellentesque leo ut, finibus sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium accumsan nulla. Aenean porta quam urna, vel accumsan tellus fermentum quis. Curabitur ullamcorper tempor metus, ut tristique orci finibus in. Sed vehicula lectus purus, lobortis condimentum magna fermentum non. Donec non nibh in arcu blandit lobortis. Aliquam vel velit sollicitudin, porta tortor quis, dapibus nisl. Maecenas a sapien arcu. Nunc consectetur sit amet nisl non sodales.

    Nunc maximus hendrerit sapien, sit amet lobortis nunc rhoncus et. Donec pretium neque lorem, nec tristique purus viverra sed. Nam accumsan turpis nec enim posuere, vitae gravida ante rutrum. Aenean et nunc nec eros dictum tempus at eget nisi. Maecenas vel tellus sem. Donec sit amet mi non nibh iaculis elementum eu vitae sem. Mauris efficitur efficitur vehicula. Donec volutpat augue nec tincidunt dignissim. Quisque nisi nunc, mollis sed massa at, condimentum lobortis nisl. Aliquam pharetra non quam at suscipit. Nam suscipit consequat est. Mauris euismod pulvinar augue vitae hendrerit. Nam accumsan faucibus elit in dapibus. Donec dapibus, risus quis auctor facilisis, tortor turpis dapibus mauris, in mollis massa risus vitae orci. Fusce viverra quis erat sit amet cursus. Proin hendrerit augue tortor.

    Donec faucibus purus sed sapien pulvinar, eget sagittis nunc consequat. Sed semper semper sapien, eu lacinia est molestie ac. Suspendisse placerat nisl lorem, et consectetur diam accumsan non. Aenean sollicitudin, erat ut interdum tristique, leo ex dapibus dui, et porta eros erat gravida urna. Proin ac pulvinar sapien. Sed tincidunt eget leo a elementum. Quisque consectetur scelerisque ex. Nam a odio et metus feugiat congue. Aliquam sed sem vitae erat dictum egestas id tempus ex. In volutpat quam mi, in aliquet massa efficitur non. Aenean molestie dictum dui. Nam bibendum justo vel leo molestie, eu suscipit erat vehicula.

    Aliquam nec mollis ipsum. Donec eget sapien tincidunt, euismod ante id, sollicitudin dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur sed rutrum massa, vel sollicitudin magna. Nulla facilisi. Duis purus neque, sagittis et magna ac, hendrerit semper augue. Vivamus commodo vel libero ullamcorper aliquam. Pellentesque sed neque sed magna semper dignissim a in elit.

    Maecenas ultricies est sagittis convallis molestie. Aliquam ut risus at lectus lobortis accumsan. Curabitur dapibus erat metus, eget ultrices turpis tincidunt nec. Vivamus bibendum dapibus lorem, id congue ligula dignissim ac. Phasellus eget dignissim orci, id aliquam erat. Nam dapibus ipsum sit amet est dignissim, vitae vestibulum nunc fermentum. Integer sollicitudin molestie scelerisque. Aenean ultrices sem et finibus efficitur. Integer ut sodales metus. Quisque consectetur lacus neque, at vehicula eros tristique id. Etiam venenatis ex a facilisis convallis. Ut auctor sagittis mollis. Praesent aliquet nisl ac lectus iaculis facilisis. Pellentesque efficitur tortor magna, vel consectetur leo pretium eu.

    Nunc leo felis, varius id tempus a, venenatis quis erat. Donec cursus mollis odio et vehicula. Sed vitae lorem ultricies, consequat ligula ac, malesuada elit. Nulla ullamcorper urna ut odio convallis tincidunt. Nunc feugiat mattis eleifend. Proin at rutrum felis, quis interdum turpis. Sed in elit ex. Donec sit amet semper sem, eu gravida diam. Aenean ut mattis felis, at sagittis orci. Vestibulum sed consectetur sem, eget interdum urna. Sed dui arcu, mattis ac nunc et, fringilla cursus nisl.

    Etiam sollicitudin imperdiet justo a hendrerit. Curabitur interdum purus id malesuada fermentum. Duis elementum neque ac massa gravida molestie vel ut libero. Integer sodales dui et ipsum iaculis efficitur. Maecenas ex nisl, viverra egestas vehicula eu, ullamcorper id purus. Praesent sodales, arcu vel ornare cursus, felis augue pulvinar nunc, ut iaculis nisi eros vel nisl. Proin imperdiet ultrices odio id fermentum. Nulla facilisi. Maecenas ut euismod nisl, eget egestas enim. Nam eget magna ex.

    Duis quis viverra lacus. Praesent quis tellus tempus, tempor est eget, tristique tortor. Praesent nibh purus, malesuada vitae tincidunt non, accumsan id odio. Integer scelerisque imperdiet leo id convallis. Phasellus id congue mauris, in elementum ipsum. Vivamus quis interdum purus. Donec commodo leo nisi, nec volutpat urna dapibus vel. Suspendisse sagittis ullamcorper posuere. Aenean sit amet accumsan felis. Aliquam id dolor a urna consequat iaculis. Suspendisse euismod eu leo maximus rutrum. Ut porta, mauris et bibendum tincidunt, risus sem iaculis magna, nec facilisis urna diam eget risus.

    Suspendisse iaculis molestie urna ut imperdiet. Nam sed lorem lectus. Sed mollis est luctus mi ornare mollis. Vestibulum posuere ultrices quam a commodo. Morbi nec velit vehicula, fermentum metus ac, malesuada risus. Nulla facilisi. Sed lacus justo, convallis molestie auctor id, luctus a orci. Nulla rutrum, diam commodo viverra ultricies, mauris sapien scelerisque velit, sed hendrerit lacus nisi et metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur lectus massa, cursus eget purus sit amet, rhoncus dapibus dui. Mauris consequat purus nulla, non molestie orci mattis a. Nulla posuere, magna ut malesuada tristique, felis lorem efficitur turpis, ac consectetur ex leo nec dui. Integer pulvinar imperdiet pretium. Cras efficitur, dolor sit amet auctor placerat, ligula diam finibus libero, a viverra ex ligula eleifend massa. Morbi id convallis purus. Phasellus vitae aliquet massa, sit amet fermentum ex.

    Vestibulum facilisis, augue a mattis facilisis, metus neque gravida justo, in ornare urna sapien at eros. Morbi erat lorem, convallis vitae vehicula vel, porta ut arcu. Praesent eget elit diam. Aenean vel neque eu sem elementum sagittis. Phasellus nec tellus ac massa vestibulum vulputate vel sed metus. Duis porttitor est in odio blandit, id rutrum sapien tincidunt. Morbi suscipit risus nisi, et bibendum mi condimentum vitae. Nam ullamcorper pharetra leo, in viverra tellus dictum ut.

    Vestibulum a dui ac est dignissim iaculis ut et nisi. Praesent laoreet dui eu risus ultrices porta. In dignissim leo ut ligula tincidunt, vitae sollicitudin risus auctor. Fusce auctor nisl vitae nulla tempus dignissim. Integer efficitur rutrum volutpat. Pellentesque consectetur rutrum ligula quis consectetur. Sed in ultrices justo. Sed suscipit enim non auctor luctus. Pellentesque viverra erat eu mollis auctor. Suspendisse vel rhoncus dui.

    Aliquam erat volutpat. Mauris finibus ipsum venenatis tincidunt accumsan. Pellentesque ac ipsum lorem. Duis vestibulum magna risus, vestibulum sodales tortor tempor in. Mauris arcu ante, laoreet eu lacus ut, elementum semper tellus. Cras ut tortor finibus, condimentum neque at, laoreet sapien. In commodo tellus vitae metus tempor vehicula. Suspendisse consequat elit vel tincidunt iaculis. Cras metus justo, congue molestie luctus sed, vestibulum nec orci. Curabitur feugiat eros et massa ullamcorper sagittis. Etiam mattis lectus at nisi bibendum fermentum. Aliquam erat volutpat. Mauris pretium lobortis faucibus. Quisque pellentesque nec dolor blandit pulvinar. Duis sit amet auctor sapien.

    Duis maximus est metus, at consequat nulla molestie id. Donec scelerisque, leo ut ornare aliquam, ex lacus consectetur purus, vitae consequat ligula velit eget tellus. Sed tincidunt felis nec eros accumsan convallis. Vivamus cursus, nisl et malesuada volutpat, tortor augue bibendum ipsum, sit amet pulvinar purus purus sed quam. Nunc in eros fermentum, imperdiet lectus id, egestas elit. Praesent in lacus nulla. In hac habitasse platea dictumst. Aliquam faucibus rutrum odio, quis placerat nisi euismod vitae. Praesent et vulputate turpis. Nunc venenatis magna sit amet orci cursus, vitae dapibus nibh molestie. Duis fringilla purus sit amet placerat luctus. Mauris a turpis dui.

    Morbi venenatis placerat ligula, a convallis lacus scelerisque vel. Vivamus aliquam sapien eu finibus feugiat. Etiam vel augue condimentum, bibendum velit sit amet, ornare sapien. Sed pharetra sodales libero, iaculis tristique elit pulvinar ac. Fusce porta ante id ligula interdum, sit amet mollis purus venenatis. Donec pretium eu metus eu elementum. Vestibulum ut ligula ut ipsum imperdiet tempus ut ut elit. Aenean porta enim quis fringilla convallis. Maecenas a iaculis tellus. Nunc at cursus sapien, ac laoreet nunc. Etiam et nisl finibus, finibus ipsum at, imperdiet metus.

    Integer rutrum cursus est, vel lacinia augue tempus at. Integer justo risus, commodo ac turpis eget, tincidunt ullamcorper odio. Sed dictum id arcu id tempor. Vestibulum mollis consectetur suscipit. Sed ornare vulputate purus sed blandit. Mauris eget turpis et velit lacinia tempor non eu eros. Vestibulum sit amet urna erat. Etiam mollis vel magna non lobortis.

    Pellentesque rhoncus nulla non quam rhoncus viverra. In maximus accumsan arcu, nec varius elit lacinia sit amet. Donec ac cursus sem. Nullam finibus egestas dolor vitae faucibus. In a tortor in neque hendrerit mollis. Sed malesuada urna at mi faucibus sodales. Aliquam id volutpat quam. In dignissim, lectus non imperdiet rutrum, velit diam pulvinar lorem, eget bibendum odio massa ut risus. Morbi nunc odio, iaculis a tortor non, suscipit blandit felis. Nullam condimentum nisl magna, quis venenatis magna malesuada sit amet. Mauris imperdiet orci non lacus vehicula consectetur. Maecenas iaculis est erat, a porttitor turpis porta sed. Vivamus sed eros nec diam faucibus dictum non tincidunt nisl. In hac habitasse platea dictumst. Etiam convallis, turpis a facilisis molestie, risus nisl ultrices nibh, ut mollis diam justo vitae nisl.

    Maecenas placerat viverra nulla et rutrum. Donec a felis vestibulum, pellentesque eros vitae, euismod turpis. Nam rutrum at magna nec bibendum. Nam dignissim libero ut velit dignissim, ut tincidunt turpis sagittis. Proin lacus purus, pellentesque ac justo eu, facilisis sagittis diam. Donec sapien turpis, egestas nec blandit in, egestas et dui. Etiam malesuada ullamcorper justo. Proin blandit metus in semper elementum.

    Donec nec dignissim lacus. Sed interdum at nunc vel vestibulum. Nam fermentum, sapien nec lacinia euismod, diam felis faucibus eros, vitae rutrum tellus lorem vitae mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis pretium tincidunt erat, vitae ullamcorper augue volutpat id. Fusce convallis, nibh in lobortis posuere, lectus dolor bibendum enim, eget porttitor leo massa nec lectus. Nam feugiat aliquet augue, at congue eros blandit et. Quisque eleifend faucibus odio. In quis augue maximus, sollicitudin ex vitae, egestas erat. Duis tempor velit ex, nec vulputate lacus euismod dignissim. Duis malesuada felis eget tellus convallis, sit amet euismod dui vestibulum.

    Aenean eget sodales dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus ex quam, suscipit vitae ligula ac, tristique ultricies nunc. Mauris in metus augue. Proin euismod massa non massa pellentesque fermentum. In auctor ornare arcu non molestie. Vestibulum sit amet eros non orci pulvinar bibendum quis quis nisl. Etiam et odio nec justo rutrum dapibus. Sed ullamcorper eget ante id tempus. Integer vitae molestie metus. Morbi tempus, augue vitae commodo vulputate, dui dolor maximus augue, ut pharetra nulla nisl nec magna.

    Integer vulputate, purus nec tristique elementum, risus augue sollicitudin nunc, vitae fermentum mauris ex ac ipsum. Phasellus id maximus risus, at bibendum ligula. In porta nisi ac ipsum pulvinar, a dictum felis mattis. Suspendisse in mauris lectus. Suspendisse potenti. Curabitur interdum dolor eget orci blandit, id venenatis ipsum elementum. Curabitur placerat leo eros, quis rutrum ipsum sodales convallis. Pellentesque ultrices lacus quis ligula mollis, non dignissim magna iaculis. Nam accumsan interdum velit quis consectetur. Aenean sed arcu elementum augue pulvinar ultrices ac non turpis.

    Etiam id porta ante. Nam semper, elit eu gravida tempor, mauris dui sagittis leo, vitae euismod metus lacus vel risus. Nam bibendum nisi leo, nec porta leo consectetur sit amet. Aliquam id convallis metus. Aliquam ut porta est. Proin ornare egestas neque, sed rutrum felis tempus non. Pellentesque egestas arcu lacus, in volutpat ante mollis nec. Nullam volutpat commodo elit eu egestas. In hac habitasse platea dictumst. Vestibulum sollicitudin metus quam, a tempor risus feugiat nec. Donec vel scelerisque nibh. Donec hendrerit lectus eget libero convallis, et porttitor arcu congue.

    Mauris eget aliquet urna. Phasellus pulvinar diam erat, non volutpat odio pellentesque id. Sed vulputate, sapien sed sagittis fermentum, nisi felis aliquet nunc, id aliquam metus magna sit amet metus. Integer finibus, lorem id bibendum consectetur, enim nibh luctus magna, et placerat tortor tortor in nisl. Donec quis odio felis. Duis enim ipsum, tincidunt et nisi non, tempor tincidunt felis. Cras euismod mi dolor, a semper dolor vehicula nec. Cras euismod justo a nisl accumsan dapibus. Etiam gravida elit in massa consectetur bibendum. Nunc non neque sit amet lectus placerat egestas sed a mauris. Donec eu efficitur tellus. Fusce vel cursus ante. Nulla facilisi. Morbi tincidunt eros odio, ut efficitur leo auctor eu. Nulla odio est, placerat sit amet gravida sit amet, aliquam a risus.

    Mauris aliquet magna efficitur auctor posuere. Nam vel ipsum sed tellus faucibus consectetur ut quis turpis. Nunc vel eleifend arcu, quis elementum ipsum. Donec finibus ex et tempus aliquam. Vestibulum ornare mattis odio, in posuere eros. Ut laoreet neque odio, sit amet convallis felis mattis imperdiet. Nulla facilisi.

    Quisque lacinia, nunc at semper condimentum, ex ipsum dictum neque, in aliquet augue justo nec orci. Nulla facilisi. Phasellus mattis massa eu turpis vestibulum, nec interdum dolor posuere. Suspendisse vulputate dapibus rutrum. Curabitur elementum maximus ipsum, eu euismod odio ultrices a. Phasellus mauris diam, pretium sed justo nec, interdum imperdiet sapien. Etiam nibh est, semper at tempor a, vestibulum ac lectus. In maximus volutpat est, a eleifend erat varius eu. Quisque varius nisi vel sodales vestibulum. Suspendisse ut metus sed odio finibus pulvinar vitae nec magna. In hac habitasse platea dictumst. Ut rhoncus lorem vitae feugiat varius.

    Cras gravida vel sem in feugiat. Sed ac ullamcorper nunc. Suspendisse magna dolor, elementum at eros vel, blandit vulputate elit. Donec id quam non justo tempus dignissim sed pellentesque tellus. Nullam egestas fringilla ipsum. Vivamus ipsum lacus, sodales sit amet massa ut, fringilla consequat felis. Sed convallis lectus sit amet risus vulputate accumsan. Aliquam in tortor nec odio sollicitudin elementum ut pharetra arcu. Nullam auctor pulvinar tempor.

    Suspendisse sed tincidunt dui, vel ornare neque. Phasellus felis sem, hendrerit sit amet feugiat eget, rhoncus id sapien. Donec lorem metus, interdum ut feugiat ut, sagittis in leo. Vestibulum ut enim molestie, blandit felis vel, faucibus diam. Sed sit amet laoreet metus, sit amet dictum lectus. Nunc tempus, urna at finibus tincidunt, sem leo feugiat quam, fermentum placerat nisi urna id arcu. Fusce tortor nisl, mattis a erat nec, aliquam condimentum nisi. Proin venenatis nec arcu lacinia dictum.

    Fusce eget ligula eu nisi scelerisque bibendum. Suspendisse pulvinar sagittis metus sit amet blandit. Proin hendrerit, tortor vel vehicula imperdiet, dui neque iaculis erat, id iaculis diam ligula non felis. Curabitur consectetur mi mi, nec eleifend neque porttitor a. Nunc a mollis erat. Etiam pretium pharetra velit, ut accumsan risus fringilla eget. Vestibulum sed blandit velit. Mauris ut mauris sit amet est bibendum pulvinar. Praesent sagittis laoreet mi, in dapibus ligula blandit id. Nunc tincidunt eros eu ultricies aliquam. Mauris vel mi sit amet justo suscipit facilisis non id turpis. Morbi sollicitudin felis quis nunc molestie tincidunt. Morbi turpis nulla, placerat luctus maximus vel, ornare et neque.

    Duis tempus felis at pulvinar suscipit. Nullam at augue lacinia justo sollicitudin gravida. Integer eleifend augue elit, eu faucibus nibh facilisis et. Sed bibendum diam eget enim vehicula faucibus. Aliquam ut lacus non arcu molestie vestibulum. Nulla nec massa nec elit sagittis blandit at eget turpis. Pellentesque vestibulum, odio eu gravida gravida, sem quam aliquet lorem, non mattis tortor metus euismod sapien. Aenean pellentesque vehicula nisl, consequat pharetra odio egestas non. Quisque vitae est odio. Curabitur dignissim vehicula arcu, vel blandit tortor pretium et. Phasellus vel vehicula lorem, vitae hendrerit sapien. Aliquam erat volutpat. Duis imperdiet lectus non lectus dapibus, at accumsan erat vulputate. Nam nec varius urna. Integer felis diam, cursus in pretium ut, viverra eu lacus.

    Donec dapibus lectus ac tellus fringilla commodo. Curabitur fermentum nisi elit, sed viverra justo ultricies et. Maecenas vitae convallis odio, eu porta dui. Aliquam condimentum lobortis justo vel convallis. Quisque efficitur eleifend posuere. Integer luctus a lectus ut tincidunt. Duis nec lacus ut eros convallis gravida.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras lacus nisi, fermentum et eleifend non, dictum non orci. Duis venenatis porta nisl nec pulvinar. Suspendisse potenti. Morbi ullamcorper egestas tortor vel pretium. Pellentesque pulvinar euismod tellus sed sagittis. Nunc efficitur sapien purus, a tempus metus condimentum eu. Donec ornare, ligula eu vehicula imperdiet, risus arcu ultricies lectus, pellentesque congue nisi augue eget justo. Pellentesque finibus risus ac urna vehicula viverra. Vivamus tincidunt, felis vel rhoncus feugiat, massa ante fringilla lorem, ac scelerisque diam lectus at diam. Etiam facilisis pellentesque mauris eu tincidunt. Sed ac libero leo.
    """
    
    func getTextArray() -> [String] {
        let newText = text
            .replacingOccurrences(of: ",", with: "")
            .replacingOccurrences(of: ".", with: "")
        
        return newText.components(separatedBy: " ")
    }
}
